# Generated by Django 5.2.1 on 2025-05-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(blank=True, default='', help_text='El servidor que se utilizará para enviar correo electrónico.', max_length=255)),
                ('email_port', models.IntegerField(default=587, help_text='Puerto a utilizar para el servidor SMTP.')),
                ('email_host_user', models.CharField(blank=True, default='', help_text='Nombre de usuario para el servidor SMTP.', max_length=255)),
                ('email_host_password', models.CharField(blank=True, default='', help_text='Contraseña para el servidor SMTP.', max_length=255)),
                ('email_use_tls', models.BooleanField(default=True, help_text='Si se debe usar una conexión TLS.')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Si se debe usar una conexión SSL implícita.')),
                ('email_fail_silently', models.BooleanField(default=False, help_text='Si los errores deben ser silenciosos al enviar correo.')),
                ('email_timeout', models.IntegerField(default=60, help_text='Tiempo de espera en segundos para operaciones de bloqueo.')),
            ],
            options={
                'verbose_name': 'Configuración de Correo',
            },
        ),
    ]
