# Generated by Django 5.2 on 2025-04-05 18:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import seguimientos.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AñoAcademico",
            fields=[
                (
                    "año_academico",
                    models.CharField(
                        max_length=7,
                        primary_key=True,
                        serialize=False,
                        validators=[seguimientos.validators.validate_año],
                    ),
                ),
            ],
            options={
                "verbose_name": "Año Academico",
                "verbose_name_plural": "Años Academicos",
                "ordering": ["-año_academico"],
            },
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nombre", models.CharField(max_length=255)),
                ("activo", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="profesor_set",
                        related_query_name="profesor",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="profesor_set",
                        related_query_name="profesor",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesor",
                "verbose_name_plural": "Profesores",
            },
        ),
        migrations.CreateModel(
            name="Ciclo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "año_academico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ciclos",
                        to="seguimientos.añoacademico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "curso",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="grupos",
                        to="seguimientos.ciclo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "curso",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="modulos",
                        to="seguimientos.ciclo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Docencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docencias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docencias",
                        to="seguimientos.grupo",
                    ),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docencias",
                        to="seguimientos.modulo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadDeTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_tema",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_de_temario",
                        to="seguimientos.modulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad de Temario",
                "verbose_name_plural": "Unidades de Temario",
                "ordering": ["numero_tema"],
            },
        ),
        migrations.CreateModel(
            name="Seguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ultimo_contenido_impartido", models.CharField(max_length=255)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ATRASADO", "Atrasado"),
                            ("AL_DIA", "Al día"),
                            ("ADELANTADO", "Adelantado"),
                        ],
                        default="AL_DIA",
                        max_length=10,
                    ),
                ),
                ("justificacion_estado", models.CharField(blank=True, max_length=255)),
                ("cumple_programacion", models.BooleanField(default=True)),
                (
                    "justificacion_cumple_programacion",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "mes",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(12),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                (
                    "evaluacion",
                    models.CharField(
                        choices=[
                            ("PRIMERA", "Primera"),
                            ("SEGUNDA", "Segunda"),
                            ("TERCERA", "Tercera"),
                        ]
                    ),
                ),
                (
                    "docencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="seguimientos.docencia",
                    ),
                ),
                (
                    "temario_actual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="seguimientos",
                        to="seguimientos.unidaddetrabajo",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="modulo",
            index=models.Index(fields=["ciclo"], name="seguimiento_ciclo_i_e36713_idx"),
        ),
        migrations.AddIndex(
            model_name="docencia",
            index=models.Index(
                fields=["profesor", "modulo"], name="seguimiento_profeso_e0cb18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="docencia",
            index=models.Index(
                fields=["grupo", "modulo"], name="seguimiento_grupo_i_4dbbb6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="docencia",
            unique_together={("profesor", "grupo", "modulo")},
        ),
        migrations.AddIndex(
            model_name="seguimiento",
            index=models.Index(fields=["mes"], name="seguimiento_mes_b761c2_idx"),
        ),
        migrations.AddIndex(
            model_name="seguimiento",
            index=models.Index(
                fields=["docencia", "mes"], name="seguimiento_docenci_09a7fa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seguimiento",
            unique_together={("docencia", "mes")},
        ),
    ]
