# Generated by Django 5.2 on 2025-05-05 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='año_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='seguimientos.añoacademico'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='seguimientos.ciclo'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='seguimientos.ciclo'),
        ),
    ]
