# Generated by Django 5.2 on 2025-04-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguimientos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="añoacademico",
            options={
                "ordering": ["-año_academico"],
                "verbose_name": "Año Academico",
                "verbose_name_plural": "Años Academicos",
            },
        ),
        migrations.AlterModelOptions(
            name="unidaddetrabajo",
            options={
                "ordering": ["numero_tema"],
                "verbose_name": "Unidad de Temario",
                "verbose_name_plural": "Unidades de Temario",
            },
        ),
        migrations.AddField(
            model_name="seguimiento",
            name="evaluacion",
            field=models.CharField(
                choices=[
                    ("PRIMERA", "Primera"),
                    ("SEGUNDA", "Segunda"),
                    ("TERCERA", "Tercera"),
                ],
                default="PRIMERA",
            ),
            preserve_default=False,
        ),
    ]
