# Generated by Django 5.2 on 2025-05-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0002_alter_ciclo_año_academico_alter_grupo_ciclo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='añoacademico',
            name='actual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='unidaddetrabajo',
            constraint=models.UniqueConstraint(fields=('numero_tema', 'modulo'), name='tema_unico'),
        ),
    ]
