# Generated by Django 5.2 on 2025-05-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0003_añoacademico_actual_unidaddetrabajo_tema_unico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciclo',
            options={'ordering': ['-año_academico', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['-ciclo__año_academico', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['-ciclo__año_academico', 'ciclo', 'curso', 'nombre']},
        ),
        migrations.AlterUniqueTogether(
            name='seguimiento',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='seguimiento',
            constraint=models.UniqueConstraint(fields=('docencia', 'mes'), name='docencia_mes_unicos'),
        ),
    ]
