# Generated by Django 5.2 on 2025-05-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0004_alter_ciclo_options_alter_grupo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='añoacademico',
            options={},
        ),
    ]
