# Generated by Django 5.2 on 2025-05-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0005_alter_añoacademico_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='añoacademico',
            options={'verbose_name': 'Año Academico', 'verbose_name_plural': 'Años Academicos'},
        ),
    ]
