# Generated by Django 5.2.1 on 2025-05-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0008_seguimiento_temario_completado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='temario_completado',
            field=models.ManyToManyField(blank=True, to='seguimientos.unidaddetrabajo'),
        ),
    ]
