# Generated by Django 5.2.1 on 2025-05-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0009_alter_seguimiento_temario_completado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordatorioemailconfig',
            name='help_text',
        ),
        migrations.AlterField(
            model_name='recordatorioemailconfig',
            name='contenido',
            field=models.TextField(default='Estimado/a {{ nombre_profesor }},\n\nLe recordamos que tiene pendiente realizar el seguimiento del mes de {{ mes }} para las siguientes docencias:\n\n{{ listado_docencias }}\n\nPuede completar los seguimientos pendientes haciendo clic en el siguiente enlace:\n{{ url_frontend }}\n\nGracias por su colaboración.\n\nEste es un correo automático, por favor no responda a esta dirección.', help_text='Variables disponibles: <br />\n- {{ nombre_profesor }}: Nombre del profesor <br />\n- {{ mes }}: Nombre del mes del seguimiento <br />\n- {{ listado_docencias }}: Lista de docencias pendientes <br />\n- {{ url_frontend }}: URL del frontend para acceder al sistema <br />\nDebes añadir por lo menos el mes y el listado de docencias al contenido. <br />\nPuedes poner las variables también en el asunto. <br />\n¡Cuidado, tienes que añadir un espacio antes y despues del nombre de cada variable!\n        '),
        ),
    ]
