# Generated by Django 5.2.1 on 2025-05-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0010_remove_recordatorioemailconfig_help_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='motivo_no_cumple_programacion',
            field=models.CharField(blank=True, choices=[('CONTENIDOS', 'Cambio en los Contenidos'), ('SECUENCIA', 'Cambio en la Secuenciación y distribución temporal de las UTs'), ('ACTIVIDADES', 'Cambio en actividades'), ('EVALUACION', 'Cambio en Evaluación')]),
        ),
    ]
