# Generated by Django 5.2.1 on 2025-05-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0011_seguimiento_motivo_no_cumple_programacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='motivo_no_cumple_programacion',
            field=models.CharField(blank=True, choices=[('CONTENIDOS', 'Cambio en los Contenidos'), ('SECUENCIA', 'Cambio en la Secuenciación y distribución temporal de las UTs'), ('ACTIVIDADES', 'Cambio en Actividades'), ('EVALUACION', 'Cambio en Evaluación')]),
        ),
    ]
