# Generated by Django 5.2.1 on 2025-05-29 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0012_alter_seguimiento_motivo_no_cumple_programacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidaddetrabajo',
            options={'ordering': ['numero_tema'], 'verbose_name': 'Unidad de Trabajo', 'verbose_name_plural': 'Unidades de Trabajo'},
        ),
    ]
