# Generated by Django 5.2.1 on 2025-06-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0013_alter_unidaddetrabajo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='justificacion_cumple_programacion',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='justificacion_estado',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='ultimo_contenido_impartido',
            field=models.CharField(),
        ),
    ]
