# Generated by Django 5.2.2 on 2025-07-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0014_alter_seguimiento_justificacion_cumple_programacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='añoacademico',
            name='actual',
            field=models.BooleanField(default=False, help_text='Define el año actual, este será el año al que tendrán acceso los usuarios en la aplicación, y será el filtro por defecto de la interfaz administrativa. Cuando se marca un año como actual se desmarca el que lo fuera previamente de manera automática.'),
        ),
    ]
