# Generated by Django 5.2.8 on 2025-11-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0015_alter_añoacademico_actual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='añoacademico',
            options={'verbose_name': 'Año Académico', 'verbose_name_plural': 'Años Académicos'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['-ciclo__año_academico', 'ciclo', 'curso', 'nombre'], 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
    ]
